build:
	g++ -Wall -Wextra etapa2.cpp heap.cpp treap.cpp -o etapa2

tests:
	./etapa2 in/test1.in
	./etapa2 in/test2.in 4
	./etapa2 in/test3.in 
	./etapa2 in/test4.in 2
	./etapa2 in/test5.in 50
	./etapa2 in/test6.in 500
	./etapa2 in/test7.in
	./etapa2 in/test8.in 4
clean:
	rm -rf etapa2